# Generated by Django 5.0 on 2024-03-11 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0002_alter_wishlist_experiences_alter_wishlist_roooms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='roooms',
            new_name='rooms',
        ),
    ]
